apiVersion: v1
kind: ServiceAccount
metadata:
  name: dscp-controller
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dscp-controller
rules:
  - apiGroups: [""]
    resources: ["pods", "configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources: ["daemonsets","deployments"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  # Add permission to execute into pods
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dscp-controller
subjects:
  - kind: ServiceAccount
    name: dscp-controller
    namespace: default
roleRef:
  kind: ClusterRole
  name: dscp-controller
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dscp-controller
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dscp-controller
  template:
    metadata:
      labels:
        app: dscp-controller
    spec:
      serviceAccountName: dscp-controller
      containers:
        - name: dscp-controller
          image: ghcr.io/owenowenisme/calico-dscp-controller/controller:main
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
