apiVersion: v1
kind: Namespace
metadata:
  name: bg-traffic

---
apiVersion: v1
kind: Service
metadata:
  name: iperf3-server-service
  namespace: bg-traffic
spec:
  selector:
    app: iperf3-server
  ports:
  - protocol: TCP
    port: 5201
    targetPort: 5201 
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iperf3-server
  namespace: bg-traffic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iperf3-server
  template:
    metadata:
      labels:
        app: iperf3-server
    spec:
      nodeSelector:
        kubernetes.io/hostname: k8sworker2.example.net
      containers:
      - name: iperf3
        image: networkstatic/iperf3
        command: ["iperf3"]
        args: ["-s", "-p", "5201", "-i", "1", "-V"]
        ports:
        - containerPort: 5201
          protocol: TCP
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
            # Request sufficient network bandwidth
          limits:
            cpu: "2000m"
            memory: "1Gi"
        readinessProbe:
          tcpSocket:
            port: 5201
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 5201
          initialDelaySeconds: 15
          periodSeconds: 20

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iperf3-client
  namespace: bg-traffic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iperf3-client
  template:
    metadata:
      labels:
        app: iperf3-client
    spec:
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      nodeSelector:
        kubernetes.io/hostname: k8smaster.example.net
      containers:
      - name: iperf3
        image: networkstatic/iperf3
        command: ["sh", "-c", "
          sleep 5;
          while true; do
            iperf3 -c iperf3-server-service.bg-traffic.svc.cluster.local -p 5201 -P 30 -t 5 -b 1G;
          done
        "]
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "2000m"
            memory: "1Gi"
